spring.application.name=almoxerifado

#SQLite
# 1. Conexão
spring.datasource.url=jdbc:sqlite:meubanco.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# 2. Dialeto (CRUCIAL para SQLite no Hibernate 6)
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# 3. Inicialização
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Força o Hibernate a não tentar adivinhar o dialeto (evita o seu erro)
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect


#H2
## Configuração de Conexão (Banco em Memória)
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
## Dialeto e JPA
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#
## Ativar o Console do H2 (Para você ver o banco no navegador)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
## Logs
#spring.jpa.show-sql=true